#crie um pipeline do github actions para uma aplicação net core

name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish --no-build --no-restore --configuration Release --output ./publish
    - name: Deploy
      uses: Azure/webapps-deploy@v2
      with:
        app-name: 'app-azure-devops'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1f1c2d3e4f5g6h7i8j9k0l1m2n3o4p5q6r7s8t9u0v1w2x3y4z5 }}
        package: ./publish
